name: flicker_api_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  web_socket_channel: ^2.4.0
  injectable: ^2.3.2
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  flutter_map: ^6.0.1
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  scrollable_positioned_list: ^0.3.8
  liquid_pull_to_refresh: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  intl_utils: ^2.8.6
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
